## Problem Statement: classify the Size_Categories using SVM

In [1]:
# SVM Cklassification
import pandas as pd
import numpy as np


In [2]:
# SVM Classification
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

from sklearn import svm
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report


from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import train_test_split, cross_val_score



## classify the Size_Categories using SVM

In [3]:
for_data = pd.read_csv('forestfires.csv')
for_data

month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain  ...  monthfeb  \
0     mar  fri  86.2   26.2   94.3   5.1   8.2  51   6.7   0.0  ...         0   
1     oct  tue  90.6   35.4  669.1   6.7  18.0  33   0.9   0.0  ...         0   
2     oct  sat  90.6   43.7  686.9   6.7  14.6  33   1.3   0.0  ...         0   
3     mar  fri  91.7   33.3   77.5   9.0   8.3  97   4.0   0.2  ...         0   
4     mar  sun  89.3   51.3  102.2   9.6  11.4  99   1.8   0.0  ...         0   
..    ...  ...   ...    ...    ...   ...   ...  ..   ...   ...  ...       ...   
512   aug  sun  81.6   56.7  665.6   1.9  27.8  32   2.7   0.0  ...         0   
513   aug  sun  81.6   56.7  665.6   1.9  21.9  71   5.8   0.0  ...         0   
514   aug  sun  81.6   56.7  665.6   1.9  21.2  70   6.7   0.0  ...         0   
515   aug  sat  94.4  146.0  614.7  11.3  25.6  42   4.0   0.0  ...         0   
516   nov  tue  79.5    3.0  106.7   1.1  11.8  31   4.5   0.0  ...         0   

     monthjan  monthjul  monthjun  monthmar  monthmay  monthnov  monthoct  \
0           0         0         0         1         0         0         0   
1           0         0         0         0         0         0         1   
2           0         0         0         0         0         0         1   
3           0         0         0         1         0         0         0   
4           0         0         0         1         0         0         0   
..        ...       ...       ...       ...       ...       ...       ...   
512         0         0         0         0         0         0         0   
513         0         0         0         0         0         0         0   
514         0         0         0         0         0         0         0   
515         0         0         0         0         0         0         0   
516         0         0         0         0         0         1         0   

     monthsep  size_category  
0           0          small  
1           0          small  
2           0          small  
3           0          small  
4           0          small  
..        ...            ...  
512         0          large  
513         0          large  
514         0          large  
515         0          small  
516         0          small  

[517 rows x 31 columns]

In [4]:
X = for_data.iloc[:, 3:30]
y = for_data.iloc[:, -1]

In [5]:
y

0      small
1      small
2      small
3      small
4      small
       ...  
512    large
513    large
514    large
515    small
516    small
Name: size_category, Length: 517, dtype: object

In [6]:
X

DMC     DC   ISI  temp  RH  wind  rain   area  dayfri  daymon  ...  \
0     26.2   94.3   5.1   8.2  51   6.7   0.0   0.00       1       0  ...   
1     35.4  669.1   6.7  18.0  33   0.9   0.0   0.00       0       0  ...   
2     43.7  686.9   6.7  14.6  33   1.3   0.0   0.00       0       0  ...   
3     33.3   77.5   9.0   8.3  97   4.0   0.2   0.00       1       0  ...   
4     51.3  102.2   9.6  11.4  99   1.8   0.0   0.00       0       0  ...   
..     ...    ...   ...   ...  ..   ...   ...    ...     ...     ...  ...   
512   56.7  665.6   1.9  27.8  32   2.7   0.0   6.44       0       0  ...   
513   56.7  665.6   1.9  21.9  71   5.8   0.0  54.29       0       0  ...   
514   56.7  665.6   1.9  21.2  70   6.7   0.0  11.16       0       0  ...   
515  146.0  614.7  11.3  25.6  42   4.0   0.0   0.00       0       0  ...   
516    3.0  106.7   1.1  11.8  31   4.5   0.0   0.00       0       0  ...   

     monthdec  monthfeb  monthjan  monthjul  monthjun  monthmar  monthmay  \
0           0         0         0         0         0         1         0   
1           0         0         0         0         0         0         0   
2           0         0         0         0         0         0         0   
3           0         0         0         0         0         1         0   
4           0         0         0         0         0         1         0   
..        ...       ...       ...       ...       ...       ...       ...   
512         0         0         0         0         0         0         0   
513         0         0         0         0         0         0         0   
514         0         0         0         0         0         0         0   
515         0         0         0         0         0         0         0   
516         0         0         0         0         0         0         0   

     monthnov  monthoct  monthsep  
0           0         0         0  
1           0         1         0  
2           0         1         0  
3           0         0         0  
4           0         0         0  
..        ...       ...       ...  
512         0         0         0  
513         0         0         0  
514         0         0         0  
515         0         0         0  
516         1         0         0  

[517 rows x 27 columns]

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3)
X_train, X_test, y_train, y_test

(       DMC     DC   ISI  temp  RH  wind  rain  area  dayfri  daymon  ...  \
 138   48.3  313.4   3.9  18.0  42   2.7   0.0  0.36       0       0  ...   
 129   46.5  691.8   8.8  15.4  35   0.9   0.0  0.00       0       0  ...   
 329  102.3  751.5   8.4  23.5  27   4.0   0.0  3.33       0       0  ...   
 444  290.0  855.3   7.4  16.2  58   3.6   0.0  9.96       1       0  ...   
 159  117.9  668.0  12.2  19.0  34   5.8   0.0  1.69       1       0  ...   
 ..     ...    ...   ...   ...  ..   ...   ...   ...     ...     ...  ...   
 421  217.7  690.0  18.0  30.8  19   4.5   0.0  0.00       0       0  ...   
 53   111.2  654.1   9.6  20.4  42   4.9   0.0  0.00       0       0  ...   
 125   46.5  691.8   8.8  20.6  24   5.4   0.0  0.00       0       0  ...   
 292  100.2  466.3   6.3  22.9  40   1.3   0.0  2.64       1       0  ...   
 68   117.9  668.0  12.2  19.6  33   6.3   0.0  0.00       1       0  ...   
 
      monthdec  monthfeb  monthjan  monthjul  monthjun  monthmar  monthmay

In [8]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((361, 27), (156, 27), (361,), (156,))

### The above data is split in train and test. We now need to check the grid search method to get the right categories/classify rightly 

### Grid Search CV

In [9]:
clf = SVC()
param_grid = [{'kernel': ['rbf'],
              'gamma': [0.5, 0.1, 0.01, 0.02],
              'C':[10, 0.1, 0.01, 0.001, 0.0001]
              }] 
gsv = GridSearchCV (clf, param_grid, cv=10)
gsv.fit(X_train, y_train)

GridSearchCV(cv=10, estimator=SVC(),
             param_grid=[{'C': [10, 0.1, 0.01, 0.001, 0.0001],
                          'gamma': [0.5, 0.1, 0.01, 0.02], 'kernel': ['rbf']}])

In [10]:
gsv.best_params_, gsv.best_score_

({'C': 10, 'gamma': 0.01, 'kernel': 'rbf'}, 0.7536036036036036)

In [11]:
clf = SVC (C=10, gamma = 0.01)
clf.fit(X_train, y_train)
y_pred=clf.predict(X_test)
acc = accuracy_score(y_test, y_pred) * 100
print('Accuracy=', acc)
confusion_matrix(y_test, y_pred)

Accuracy= 74.35897435897436


array([[  2,  36],
       [  4, 114]])

In [12]:
y_pred

array(['small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'large', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'large', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'large',
       'small', 'sma

In [13]:
clf2 = SVC()
param_grid = [{'kernel': ['rbf'],
              'gamma': [0.01, 0.2, 1.0, 10, 100],
              'C':[ 5, 20, 30, 40, 50]
              }] 
gsv1 = GridSearchCV (clf, param_grid, cv=10)
gsv1.fit(X_train, y_train)

GridSearchCV(cv=10, estimator=SVC(C=10, gamma=0.01),
             param_grid=[{'C': [5, 20, 30, 40, 50],
                          'gamma': [0.01, 0.2, 1.0, 10, 100],
                          'kernel': ['rbf']}])

In [14]:
gsv1.best_params_, gsv1.best_score_

({'C': 20, 'gamma': 0.01, 'kernel': 'rbf'}, 0.7536036036036036)

In [15]:
clf2 = SVC (C=5, gamma = 0.01)
clf2.fit(X_train, y_train)
y_pred1=clf2.predict(X_test)
acc = accuracy_score(y_test, y_pred1) * 100
print('Accuracy=', acc)
confusion_matrix(y_test, y_pred1)

Accuracy= 74.35897435897436


array([[  2,  36],
       [  4, 114]])

In [16]:
y_pred1

array(['small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'large', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'large', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'large',
       'small', 'sma

In [17]:
clf3 = SVC()
param_grid = [{'kernel': ['rbf'],
              'gamma': [2.5, 5, 15, 20, 30],
              'C':[ 5, 20, 30, 40, 50]
              }] 
gsv2 = GridSearchCV (clf, param_grid, cv=10)
gsv2.fit(X_train, y_train)


GridSearchCV(cv=10, estimator=SVC(C=10, gamma=0.01),
             param_grid=[{'C': [5, 20, 30, 40, 50],
                          'gamma': [2.5, 5, 15, 20, 30], 'kernel': ['rbf']}])

In [18]:
gsv2.best_params_, gsv2.best_score_

({'C': 5, 'gamma': 2.5, 'kernel': 'rbf'}, 0.7258258258258259)

In [19]:
clf3 = SVC (C=5, gamma = 2.5)
clf3.fit(X_train, y_train)
y_pred2=clf3.predict(X_test)
acc = accuracy_score(y_test, y_pred2) * 100
print('Accuracy=', acc)
confusion_matrix(y_test, y_pred2)

Accuracy= 75.64102564102564


array([[  0,  38],
       [  0, 118]])

### Trying the various combination has resulted in concluding to use C = 5, gamma=0.01

In [20]:
y_pred1

array(['small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'large', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'large', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'small',
       'small', 'small', 'small', 'small', 'small', 'small', 'large',
       'small', 'sma

### Problem 2: Prepare a classification model using SVM for salary data

In [ ]:
test_data = pd.read_csv('SalaryData_Test(1).csv')
test_data

In [ ]:
train_data = pd.read_csv('SalaryData_Train.csv')
train_data

In [ ]:
total_data = [test_data, train_data]

sal_data = pd.concat(total_data)
sal_data

In [ ]:
sal_data1= pd.get_dummies(sal_data, columns=['education', 'maritalstatus', 'occupation','race', 'sex', 'workclass','relationship' ])
sal_data1

In [ ]:
def swap_columns(sal_data1, Salary, age):
    col_list = list(sal_data1.columns)
    x, y = col_list.index(Salary), col_list.index(age)
    col_list[y], col_list[x] = col_list[x], col_list[y]
    sal_data1 = sal_data1[col_list]
    return sal_data1
sal_data2 = swap_columns(sal_data1, 'Salary', 'age')
print (sal_data2)

In [ ]:
sal_data2= sal_data2.drop('native', axis=1)

In [ ]:
X = sal_data2.iloc[:, 1:64]
y = sal_data2.iloc[:, 0]

In [ ]:
y

In [ ]:
X

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3)
X_train, X_test, y_train, y_test

In [ ]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

### We will try the GSV method to get the right categories

### Grid Search CV 

In [ ]:
clf = SVC()

In [ ]:
param_grid = [{'kernel': ['rbf'],
              'gamma': [0.5, 0.1, 0.01, 0.02],
              'C':[10, 0.1, 0.01, 0.001, 0.0001]
              }]
gsv = GridSearchCV (clf, param_grid, cv= 10)
gsv.fit(X_train, y_train)

In [ ]:
gsv.fit(X_train, y_train)

In [ ]:
gsv.best_params_, gsv.best_score_

In [ ]:
clf = SVC (C=10, gamma = 0.01)
clf.fit(X_train, y_train)
y_pred=clf.predict(X_test)
acc = accuracy_score(y_test, y_pred) * 100
print('Accuracy=', acc)
confusion_matrix(y_test, y_pred)

In [ ]:
y_pred